### PR TITLE
 upgrade tomcat 6 -> tomcat 7

### PR DESCRIPTION
**Pull request by SiKing**
This starts with no warnings.

### CODE REVIEW

**Comment by SiKing** [comment]
This needs https://github.com/turnkeylinux/common/pull/28

**Comment by SiKing** [comment]
I should have also mentioned: I built this on top of the TKLDev14rc1.

**Comment by JedMeister** [comment]
As per my [comments on your other pull request](https://github.com/turnkeylinux/common/pull/28#issuecomment-106122017) I think that we need to tidy up the conflicting common code before we should merge this. 

I had already [updated this code](https://github.com/JedMeister/tomcat/tree/jessie-update) but I hadn't issued a pull request (on the Tomcat appliance or the Tomcat-Apache appliance) yet... While the updates each of us has done are almost identical, yours does appear to go a little further. Once the conflict on your other pull request is resolved then I suggest that this pull request is merged this I will do a diff against the updated code and do a pull request if relevant (I doubt it TBH)...

**Comment by SiKing** [comment]
One more comment, besides https://github.com/turnkeylinux/common/pull/28#issuecomment-106371940 I tried to get tomcat-apache as well, but at this point I do not understand how that one works without depending on the tomcat appliance. Some of the scripts that I fixed on tomcat are outright missing on tomcat-apache. You can see my changes here https://github.com/SiKing/tomcat-apache , but at this time that appliance does not even start.

**Comment by JedMeister** [comment]
Ok cheers. I'll take care of that too. IIRC I have actually completed that one. Over the next couple of days I will tidy all this up... :smile: 

Thanks again for your contributions though! The more the merrier! :+1:

**Comment by SiKing** [comment]
One last comment: I think the convenience script "oracle-java-installer" might be useful for other appliances as well, and as such might be more appropriate in the common/overlay? But I did not want to "pollute" every single appliance you guys have. :o

Again, Thank You.

**Comment by JedMeister** [comment]
Yes good idea. 

I think that we could put it in the common/overlay/tomcat. I think that is where it is most relevant!? Then it will go in all Tomcat based appliances. I might preface it with 'turnkey-' though (so it will be 'turnkey-oracle-java-installer'). Then tab complete will make it easier for people to find.

**Pull request closed without merging**
